# Generated by Django 4.2.3 on 2023-07-21 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from django.contrib.auth.admin import User

from .. import models as mymodels


def populate_rooms(apps, schema_editor):
    rooms = ['First room', 'Second room', 'Third room']
    slugs = ['room1', 'room2', 'room3']
    for i in range(len(rooms)):
        obj = mymodels.Room(name=rooms[i], slug=slugs[i])
        obj.save()

def generate_superuser(apps, schema_editor):
    superuser = User()

    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = 'admin'
    superuser.email = 'admin@admin.net'
    superuser.set_password('admin')
    superuser.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatroom.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),

        migrations.RunPython(populate_rooms),
        migrations.RunPython(generate_superuser)

    ]
